# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# All boards will have the -DZMK_CONFIG=/home/alealfaro/GeekieStuff/dyi-keyboard/fw/zmk-config/config -DZMK_EXTRA_MODULES=/home/alealfaro/GeekieStuff/dyi-keyboard/fw/zmk_playground_module
#
#

 # include:
 #   - board: nice_nano
 #     shield: corne_left
 #     snippet: studio-rpc-usb-uart
 #     cmake-args: -DCONFIG_ZMK_STUDIO=y
 #     artifact-name: nice_nano_corne_left
---
 include:
   - board: nice_nano_mcuboot/nrf52840
     shield: corne_left
     snippet: serial-console
     artifact-name: nice_nano_corne_left
   - board: nice_nano_mcuboot/nrf52840
     shield: corne_right
     snippet: serial-console
     artifact-name: nice_nano_corne_right

---
 include:
   - board: sparkfun_pro_micro_rp2350/rp2350a/m33
     shield: corne_keyboard_zmk_left
     snippet: serial-console
     artifact-name: corne_rpico2_left
   - board: sparkfun_pro_micro_rp2350/rp2350a/m33
     shield: corne_keyboard_zmk_right
     snippet: serial-console
     artifact-name: corne_rpico2_right
